\newpage

# Conclusion

We trained a Deep Q-Network to learn and play Can't Stop. However, the DQN was not successful at playing the game well as it failed to meet the performance baseline. We expected the DQN to win a majority of games against the random player, however we saw a $21.4\%$ average win rate. There are many possibilities as to why the model failed to meet the performance baseline, such as poor hyperparameter tuning, an over complicated training environment, or using an ineffective learning algorithm. 

The main problem seen during the training process was overestimation of the reward values. This was caused by setting the discount factor too high, forcing the model to chase and overestimate long term rewards unachievable in a typical game. While this was adjusted for the last $3^{rd}$ of the training, as seen in Figures \@ref(fig:rewardandq4)-\@ref(fig:rewardandq6), the win rate did not experience enough of an impact. This is likely because the amount of time spent training with the parameter set too high could not be offset with the amount of total training time left. The model spent majority of its time trying to do a futile task, and this likely led to the model creating bad connections with its features. The majority of the model's core knowledge is learned in the initial training stages, so spending that crucial training time learning a very ineffective strategy was a significant hindrance on the model's performance.

The training environment we created involved the model playing games against 7 different playstyles at random to prevent the model from overfitting a hyperspecific strategy. This possibly had the opposite effect as the strategy the model developed was not successful against any playstyle. Training against one or two approaches and the baseline could create a better performing model, with the other playstyles being used for testing only to evaluate the model. 
Along with a difficult learning environment, reducing the number of features could also improve the model's performance. Since many of the features had no impact or a negative impact on the performance, reducing the features could allow the model to concentrate on a smaller set of features. Another alternative is to use an ensemble learning technique, either bagging or boosting. From James, Witten, Hastie, and Tibshirani (2021), bagging is taking many subsets of the training data (or features), and build separate models for each set, and combine the outputs to make a prediction. Boosting is similar except the separate models are added sequentially into the main model. Both methods reduce the variance and overfitting bias in the model.

With time, the model could be retrained using a smaller discount factor that increases with performance. Since Can't Stop is a shorter game, models could benefit from a smaller discount factor. Another possible parameter change for future training is increasing the learning rate, which was not able to be tested during this analysis. Increasing the step-size could reduce training time and improve performance as the model uses new information more quickly. Along with these changes to the parameters, reducing the scope of the training environment with less playstyles would be tested. Giving the model a simpler environment to train against could be similar in the approach of studying the toy versions of games to find strategies. The overestimation seen in this analysis is a common issue with training DQN models, so a recent solution is the Double Q-learning algorithm proposed by Van Hasselt, Guez, and Silver (2016). This works by giving the model two Q-tables, one for q-values of the best action choice and the other to evaluate the q-value of the action from the first table. This implementation reduces overestimation however is more computationally expensive compared to standard Q-learning. As discussed above, using the bagging method could also help the model develop the features better.
With more time and computing power, future work using the double Q-learning method with bagging, reducing the training environment, and better parameterization could produce a better performing model with a unique strategy to analyze and learn from.